### PR TITLE
refactor: partially invalid exception thrown

### PR DESCRIPTION
**Pull request by LiuXing-R**
1, Remove useless `PolicyException`
2, The `PolicyException` thrown is meaningful after the custom policy parameter is judged null

### CODE REVIEW

**Comment by davewichers** [comment]
@spassarop - what do you think of this proposed change?

**Comment by spassarop** [comment]
Changes make sense. The throws in constructors were already useless, the null policy exception moved a level below is still valid and maybe cleaner (avoids repeating the throw).

The one change I'm not sure is the `main` method on AntiSamyDOMScanner and not because it's useful, it's clearly not. But for if there is a real reason for an empty `main` on the project. @davewichers, is there any reason for en empty `main` to exist? Something about compulsary executable class for the Maven pipeline or whatever? If it can be deleted then the PR is all right.

**Comment by LiuXing-R** [comment]
Two useless throws were missed.

**Comment by LiuXing-R** [comment]
@davewichers 
I've found that `Antisamy` has a lot of redundant code, and I'd be happy to refactor it if you agree.

**Comment by davewichers** [comment]
@spassarop - I doubt the main() is needed. @LiuXing-R - I'm going to accept this pull request. If you want to work on refactoring to clean up the code, feel free. Thanks!

**Pull request merged**
