### PR TITLE
[site] Switch to fluido using owasp logo / add index page to site report

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by davewichers** [comment]
@hazendaz - Thanks for this! Looks great. 1 question: Is there a way to specify the size of the logo included at the top. The OWASP logo looks good but it is so BIG. Any way to specify that it be displayed smaller?

**Comment by hazendaz** [comment]
I'm not sure on the sizing.  Possibly need to use mspaint and resize there or maybe a smaller one is available.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by davewichers** [comment]
I've merged these changes into the 1.5.11 release branch we are working on now. As such, I'm closing this pull request as these changes will get merged into master when that release is complete.

**Comment by hazendaz** [comment]
Thanks.  Glad this worked out for you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
