### PR TITLE
 Remove multiple definition of tags on policy files

### PR DESCRIPTION
**Pull request by spassarop**
- The "clip" property was duplicated.
- "col" tag had two definitions, one of them a plain "validate" action.
- Policies changed are: antisamy, anythinggoes, myspace and ebay.

This fixes issue #53 .

### CODE REVIEW

**Comment by davewichers** [comment]
@spassarop - I created a 1.5.11 branch awhile a go. Sorry I forgot to mention that. Can you change the target of this pull request to go into that branch? That way all changes are there before we merge them into master when we do the next release. And please do so with any other proposed changes.

@nahsra - Arshan - please review these policy file changes and let us know if you are cool with them. Should only take a few minutes to review.

**Comment by spassarop** [comment]
It's ok, I forgot to ask too. I'll change this.

**Comment by davewichers** [comment]
@spassarop - I see that you did this: "spassarop changed the base branch from master to 1.5.11 6 days ago"

But when I try to Merge the pull request it says: "Add more commits by pushing to the master branch on spassarop/antisamy.", which implies the target of the merge will be master, not 1.5.11.  Can you fix that? or am I reading this wrong?

**Comment by spassarop** [comment]
I think that is because the source branch in my fork is still master. So I can still add commits to the PR if I push them there. But the target branch is now nahsra:1.5.11.

**Comment by kwwall** [comment]
@spassarop -- A few days ago, in some release notes associated with the OWASP Java Encoder project, Jeremy Long (@jeremylong) sent something out just prior to the Java Encoder 1.2.3 release that discussed how to update your local branches from 'master' to 'main'. (I apparently deleted that email and have since empted my 'trash' so I no longer seem to have it.) But perhaps if you ask nice, @jeremylong might post those git instructions here. ;-)

**Comment by spassarop** [comment]
@davewichers, @kwwall - Wouldn't it be cleaner if I just redo the changes in my fork on the 1.5.11 branch and make a new PR to this repo's 1.5.11 branch? Or maybe branch from spassarop:1.5.11 and PR that to nahsra:1.5.11 as I have another PR to do.

In that case, this PR would be closed (or maybe deleted). I just noticed there are other commits that shouldn't be there 😅

**Comment by kwwall** [comment]
@spassarop - I'm not sure if it would be "cleaner", but it probably would be faster!

**Comment by davewichers** [comment]
@spassarop - per: "I just noticed there are other commits that shouldn't be there", I'm closing this pull request. Please submit a new one to the current 1.11 branch. Thanks.

**Pull request closed without merging**
