### PR TITLE
Adding the cached-item to the cachedItems Queue in the scan method of…

### PR DESCRIPTION
**Pull request by dharmendra027**
To fix the **performance degradation**(by 45-50%) issue in case of **SAXScancer**, adding cached-item to the cachedItems queue .

### CODE REVIEW

**Comment by dharmendra027** [comment]
Any feedback on my PR ? Do I need to describe further the purpose of this fix ?

**Comment by dharmendra027** [comment]
Hi @davidbarbrowatwork can you please review this pull request.

**Comment by davewichers** [comment]
Hey @dharmendra027, given no response from @davidbarbrowatwork, can you contact me directly at dave dot wichers at owasp dot org? I'd like to create some test cases around this functionality to verify it works as expected now (but maybe slower), and then still works, but faster with your suggested change, so we can get this suggestion merged in with confidence that it works/doesn't break anything.

**Comment by dharmendra027** [comment]
Hey @davewichers , do i need to create account at owasp.org to contact you?

**Comment by davewichers** [comment]
No. Just email me directly at: dave dot wichers at owasp dot org.

**Comment by davewichers** [comment]
This requested change was committed in a separate change.

**Pull request closed without merging**
